_security_check:
    pattern:  /facebook/login_check/
    defaults: { _controller: AiloveFacebookBundle:Facebook:index }
_security_logout:
    pattern:  /profile/logout
    defaults: { _controller: AiloveFacebookBundle:Facebook:index }

fb_login:
    pattern:  /fb/login
    defaults: { _controller: AiloveFacebookBundle:Facebook:login }
fb_connect:
    pattern:  /fb/conect
    defaults: { _controller: AiloveFacebookBundle:Facebook:connect }


