_fb_security_check:
    pattern: /login_check/
    defaults: { _controller: 'FOSUserBundle:FOSUserSecurity:check' }
_fb_connect:
    pattern: /login/connect/
    defaults: { _controller: 'AiloveFacebookBundle:Social:connect' }
_fb_login:
    pattern: /login/
    defaults: { _controller: 'AiloveFacebookBundle:Social:login' }

