parameters:
#    ailove_facebook.example.class: Ailove\FacebookBundle\Example

services:
#    ailove_facebook.example:
#        class: %ailove_facebook.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

  fos.facebook.user:
      id: fos.facebook.user
      class: Ailove\FacebookBundle\Security\Facebook\User\FacebookUserProvider
      arguments: [@fos_facebook.api, @fos_user.user_manager, @validator, @service_container]